// 서버 내부 동작(부트스트랩/DB/OpenClaw)에서 사용하는 문구와 상수 카탈로그
// Slack 사용자 문구와 분리해 운영/디버깅 문구가 UX에 섞이지 않게 한다.

// start 유스케이스 내부 제어값/판별값 상수
export const ROOM_START_SERVICE_CONSTANTS = {
  pendingStartThreadTs: "PENDING_START_THREAD_TS",
  autoGeneratedTopic: "주제 미정",
  sqliteConstraintErrorCode: "SQLITE_CONSTRAINT",
  sqliteConstraintUniqueErrorCode: "SQLITE_CONSTRAINT_UNIQUE",
  sqliteConstraintErrno: 19,
  activeSessionConstraintIndexName: "idx_room_sessions_active_per_channel",
  activeSessionConstraintColumnName: "room_sessions.start_channel_id",
  activeWatchTargetConstraintIndexName: "idx_room_watch_targets_active_per_channel",
  activeWatchTargetConstraintColumnName: "room_watch_targets.channel_id",
  followupNoticeUnknownError: "후속 안내 전송 중 알 수 없는 오류"
} as const;

// launch 유스케이스 내부 제어값/판별값 상수
export const ROOM_LAUNCH_SERVICE_CONSTANTS = {
  pendingLaunchThreadTs: "PENDING_LAUNCH_THREAD_TS",
  followupNoticeUnknownError: "라운드 완료 안내 전송 중 알 수 없는 오류"
} as const;

// OpenClaw 연동 기본값/스케줄 설정
export const ROOM_OPENCLAW_DEFAULTS = {
  eventsFilePath: "./data/openclaw-room-events.ndjson",
  modeTtlMinutes: 10,
  autoQuestionIntervalMinutes: 30,
  outboxDispatchIntervalMs: 5000,
  requestTimeoutMs: 12_000,
  liveReplyMaxRetries: 2,
  liveReplyRetryDelayMs: 5000,
  agentId: "main",
  lifecycleScanIntervalMs: 60_000,
  outboxBatchSize: 100,
  lifecycleBatchSize: 100
} as const;

// OpenClaw 연동 계층에서 사용하는 공통 문구
export const ROOM_OPENCLAW_MESSAGES = {
  invalidPositiveInteger: (name: string): string => `${name}는 0보다 큰 정수여야 합니다.`,
  invalidNonNegativeInteger: (name: string): string => `${name}는 0 이상 정수여야 합니다.`,
  missingThreadIdentifiers: "스레드 식별자(channelId/threadTs/messageTs)가 없어서 이 메시지는 건너뜁니다.",
  missingMessageText: "메시지 본문(text)이 비어 있어서 실시간 답변 생성을 건너뜁니다.",
  missingPlanningWatchTargetForLaunchOff: "launch OFF 처리 대상인 planning watch target을 찾지 못했습니다.",
  invalidOutboxPayload: "OpenClaw outbox payload 파싱에 실패했습니다.",
  invalidChatResponsePayload: "OpenClaw Chat 응답 형식이 예상과 다릅니다.",
  openclawHttpRequestFailed: "OpenClaw Chat API 호출에 실패했습니다.",
  liveReplySystemPrompt:
    "너는 택배라는 이름의 검정 고양이 AI 비서다. 한국어로 짧고 실무적으로 답한다. " +
    "필요하면 가볍게 친근한 톤을 쓰되, 결론과 다음 행동을 먼저 제시한다.",
  startKickoffSystemPrompt:
    "너는 택배라는 이름의 검정 고양이 AI 비서다. " +
    "한국어 존댓말로 짧고 친근하게 답하고, 회의 준비를 빠르게 시작하도록 질문을 이끈다.",
  startKickoffUserPrompt:
    "사용자가 /room start를 실행했다. " +
    "새 스레드 첫 메시지로 4줄 이내로 답해라. " +
    "1) 짧은 인사 2) 어떤 회의인지 질문 3) 목표/제약/완료기준 요청 4) 바로 답하기 쉽게 마무리.",
  unknownDispatchError: "OpenClaw outbox 디스패치 중 알 수 없는 오류",
  unknownLifecycleError: "OpenClaw 수명/트리거 스케줄 처리 중 알 수 없는 오류",
  unknownLiveReplyError: "OpenClaw 실시간 답변 처리 중 알 수 없는 오류",
  unknownStopError: "OpenClaw 스케줄러 종료 중 알 수 없는 오류",
  forbiddenPayloadField: (field: string): string => `OpenClaw 이벤트 payload에 금지 필드가 있습니다: ${field}`
} as const;

// 앱 부트스트랩/환경검증 문구
export const ROOM_APP_MESSAGES = {
  missingRequiredEnvironmentVariable: (name: string): string => `필수 환경변수가 비어 있어요: ${name}`,
  invalidPort: "PORT는 0보다 큰 숫자여야 해요.",
  unknownBootstrapError: "부트스트랩 중 알 수 없는 오류가 발생했어요.",
  unknownShutdownError: "종료 처리 중 알 수 없는 오류가 발생했어요."
} as const;

// SQLite 계층에서 사용하는 오류 문구
export const ROOM_SQLITE_MESSAGES = {
  notConnected: "SqliteClient가 연결되지 않았습니다. connect() 이후에 데이터베이스를 사용해 주세요.",
  createPreparedSessionFailed: "PREPARED 세션 생성에 실패했습니다.",
  updatePreparedSessionStartThreadFailed: "PREPARED 세션의 start 스레드 정보를 갱신하는 데 실패했습니다.",
  claimPreparedSessionForLaunchFailed: "launch 실행을 위한 PREPARED 세션 선점에 실패했습니다.",
  rollbackLaunchClaimFailed: "launch 선점 롤백에 실패했습니다.",
  updateSessionToRunningFailed: "세션 상태를 RUNNING으로 변경하는 데 실패했습니다.",
  updateSessionToDecidedFailed: "세션 상태를 DECIDED로 변경하는 데 실패했습니다.",
  deleteSessionFailed: "세션 삭제에 실패했습니다.",
  deleteWorkerRoundFailed: "워커 라운드 삭제에 실패했습니다.",
  createBriefingFailed: "브리핑 생성에 실패했습니다.",
  createWorkerRoundFailed: "워커 라운드 생성에 실패했습니다.",
  parseWorkerRoundCandidatesFailed: "워커 라운드 후보안 파싱에 실패했습니다.",
  createWatchTargetFailed: "OpenClaw 감시 대상 생성에 실패했습니다.",
  turnOffWatchTargetFailed: "OpenClaw 감시 대상 OFF 전환에 실패했습니다.",
  incrementWatchTargetMessageCountFailed: "OpenClaw 감시 대상 메시지 카운트 증가에 실패했습니다.",
  claimQuestionTriggerFailed: "OpenClaw question 트리거 선점에 실패했습니다.",
  createThreadMessageMetadataFailed: "OpenClaw 스레드 메시지 메타데이터 저장에 실패했습니다.",
  createOutboxEventFailed: "OpenClaw outbox 이벤트 저장에 실패했습니다.",
  parseOutboxPayloadFailed: "OpenClaw outbox payload 파싱에 실패했습니다.",
  markOutboxDispatchedFailed: "OpenClaw outbox DISPATCHED 마킹에 실패했습니다.",
  markOutboxRetryFailed: "OpenClaw outbox 재시도 마킹에 실패했습니다."
} as const;

// Slack 어댑터 계층에서 사용하는 오류 문구
export const ROOM_SLACK_MESSAGES = {
  missingThreadTimestamp: "Slack postMessage 응답에 스레드 타임스탬프(ts)가 없어요."
} as const;

