// 로그 이벤트명 카탈로그
// 이벤트 키를 중앙화해 로그 분석 시 필드 분산을 방지한다.

export const ROOM_LOG_EVENT_NAMES = {
  slackCommandBound: "slack.command.bound",
  slackCommandAckCompleted: "slack.command.ack.completed",
  slackCommandAckFailed: "slack.command.ack.failed",
  slashCommandAckSkipped: "slack.command.ack.skipped",
  slackCommandPostAckCompleted: "slack.command.post_ack.completed",
  slackMessageEventBound: "slack.message_event.bound",
  slackCommandUnhandledFailure: "slack.command.unhandled_failure",
  slackMessageUnhandledFailure: "slack.message.unhandled_failure",
  slashCommandFollowupReplaceSkipped: "slack.command.followup.replace.skipped",
  slashCommandFollowupReplaceFailed: "slack.command.followup.replace.failed",
  slashCommandFollowupDeleteFailed: "slack.command.followup.delete.failed",
  roomCommandInvalid: "room.command.invalid",
  roomCommandCompleted: "room.command.completed",
  roomCommandPhaseCompleted: "room.command.phase.completed",
  roomCommandFailed: "room.command.failed",
  roomCommandThreadNoticeFailed: "room.command.thread_notice_failed",
  roomStartPhaseCompleted: "room.start.phase.completed",
  roomStartCompleted: "room.start.completed",
  roomStartKickoffNoticeFailed: "room.start.kickoff_notice_failed",
  roomStartReservationRollbackSkipped: "room.start.reservation_rollback_skipped",
  roomStartReservationRollbackFailed: "room.start.reservation_rollback_failed",
  roomLaunchPhaseCompleted: "room.launch.phase.completed",
  roomLaunchCompleted: "room.launch.completed",
  roomLaunchFollowupNoticeFailed: "room.launch.followup_notice_failed",
  roomLaunchThreadMetadataUpdateFailed: "room.launch.thread_metadata_update_failed",
  roomLaunchRoundCleanupFailed: "room.launch.round_cleanup_failed",
  roomLaunchClaimRollbackFailed: "room.launch.claim_rollback_failed",
  roomStopCompleted: "room.stop.completed",
  openclawRoomModeOnCompleted: "openclaw.room_mode_on.completed",
  openclawRoomModeOffCompleted: "openclaw.room_mode_off.completed",
  openclawRoomModeOffSkipped: "openclaw.room_mode_off.skipped",
  openclawThreadMessageIgnored: "openclaw.thread_message.ignored",
  openclawThreadMessageIngested: "openclaw.thread_message.ingested",
  openclawQuestionTriggerQueued: "openclaw.question_trigger.queued",
  openclawTtlOffQueued: "openclaw.ttl_off.queued",
  openclawTtlNoticePosted: "openclaw.ttl_notice.posted",
  openclawTtlNoticeFailed: "openclaw.ttl_notice.failed",
  openclawLifecycleFailed: "openclaw.lifecycle.failed",
  openclawOutboxDispatched: "openclaw.outbox.dispatched",
  openclawOutboxRetryScheduled: "openclaw.outbox.retry_scheduled",
  openclawOutboxDispatchFailed: "openclaw.outbox.dispatch_failed",
  openclawChatRequestCompleted: "openclaw.chat.request.completed",
  openclawChatRequestFailed: "openclaw.chat.request.failed",
  openclawThreadEventCompleted: "openclaw.thread_event.completed",
  openclawLiveReplySkipped: "openclaw.live_reply.skipped",
  openclawLiveReplyCompleted: "openclaw.live_reply.completed",
  openclawLiveReplyRetryScheduled: "openclaw.live_reply.retry_scheduled",
  openclawLiveReplyFailed: "openclaw.live_reply.failed",
  openclawSchedulerStarted: "openclaw.scheduler.started",
  openclawSchedulerStopped: "openclaw.scheduler.stopped",
  openclawSchedulerStopFailed: "openclaw.scheduler.stop_failed",
  appStopping: "slack-room-orchestrator.stop",
  appStopFailed: "slack-room-orchestrator.stop_failed",
  appStarted: "slack-room-orchestrator.start"
} as const;

